services:
  db:
    image: "postgres"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-todo_test}
      POSTGRES_USER: ${POSTGRES_USER:-todo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-todo}
    ports:
      - "5433:5432"
